plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "sig/**/*"
    - "vendor/**/*"
    - "specs/**/*"
    - "examples/**/*"
    - "Gemfile"

# Gemspec の development dependency は gemspec 内で管理
Gemspec/DevelopmentDependencies:
  Enabled: false

# 日本語コメントを許容
Style/AsciiComments:
  Enabled: false

# frozen_string_literal は全ファイルで必須
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# プロジェクトの特性上、メソッドの行数制限を緩める
Metrics/MethodLength:
  Max: 20

# CsvImporter のブロック長は許容
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "jp_address_complement.gemspec"

# モジュール・クラス長の上限を緩める（Repository 実装用）
Metrics/ClassLength:
  Max: 150

# RSpec の describe/context は DSL の性質上緩める
RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 5

# Generator・タスク・パフォーマンステストはクラス記述不要
RSpec/DescribeClass:
  Exclude:
    - "spec/generators/**/*"
    - "spec/tasks/**/*"
    - "spec/performance_spec.rb"

# RSpec spec パスのディレクトリ構成を許容（spec/ 直下に rb ファイルを置きたい場合）
RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/SpecFilePathSuffix:
  Enabled: false

# context の日本語記述の等を許容
RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - 正常な
    - 不正な
    - "nil"
    - 先頭
    - 7桁
    - 4桁
    - 8桁
    - 同じ
    - 異なる

# AddressRecord は Data.define の返り値で定数名規則を強制できない
Naming/ConstantName:
  Exclude:
    - "lib/jp_address_complement/address_record.rb"

# Gem エントリーポイントはトップレベルドキュメントを必須としない
Style/Documentation:
  Exclude:
    - "lib/jp_address_complement.rb"
    - "spec/**/*"

# rbs-inline の #: Type 注釈は # の直後に : が来るため LeadingCommentSpace と競合（FR-010, T008）
Layout/LeadingCommentSpace:
  Exclude:
    - "lib/jp_address_complement/configuration.rb"
    - "lib/jp_address_complement/importers/csv_importer.rb"
    - "lib/jp_address_complement/normalizer.rb"
    - "lib/jp_address_complement/version.rb"

# マジックコメント直後の空行: rbs_inline: disabled は 1 行で理由まで書くため空行を入れない（T008）
Layout/EmptyLineAfterMagicComment:
  Exclude:
    - "lib/jp_address_complement/address_record.rb"

# CsvImporter の parse_row は列数が多い CSV のパースのためやむを得ず複雑になる
Metrics/AbcSize:
  Exclude:
    - "lib/jp_address_complement/importers/csv_importer.rb"

Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/jp_address_complement/importers/csv_importer.rb"

Metrics/PerceivedComplexity:
  Exclude:
    - "lib/jp_address_complement/importers/csv_importer.rb"
